<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>MagicProxyPrinter</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <Version>$(GitTagVersion)</Version>
    <FileVersion>$(GitTagVersion)</FileVersion>
    <AssemblyVersion>$(GitTagVersion)</AssemblyVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cocona.Lite" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="NLog" />
    <PackageReference Include="NLog.Extensions.Logging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="nlog.config" />
  </ItemGroup>

  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
	
</Project>
